#spring.application.name=employee-service
#server:
#  port: 8082
#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#      
#  h2:
#    console:
#      enabled: true
#
 

#  datasource:
#    url: jdbc:h2:mem:testdb
#spring:
#  application:
#    name: employee-service
#  config:
#    import: optional:configserver:http://localhost:8888
##    

server:
  port: 8084

spring:
  application:
    name: employee-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # options are none, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Update the dialect to MySQL8Dialect

        
#spring.application.name=employee-service
##
##spring.datasource.url=jdbc:mysql://mysql-container:3306/mysql
##spring.datasource.username=root
##spring.datasource.password=root
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.show_sql=true
